### ISSUE TITLE
I want this function to be able to take all of the words that are in the trump article and not in the biden article and make the same type of histogram we did to begin with in Analyze Book. This way I can show the most used words that are significant to each article 

### ISSUE THREAD

**Issue by mbouffard1** [mbouffard1/text-mining#1]
https://github.com/mbouffard1/text-mining/blob/84a9a00c84daa97735deeecd2220c58c170b7c96/work%20with%20data/analyze_trump.py#L60-L72

**Comment by lzblack** [comment]
In function `exclusive_dict`, change both `.items()` to `.keys()` (as you mentioned in docstring, you need all the keys).

Then in `main()`
```
print(exclusive_dict(hist,biden))
```
should print all the words that are in `hist` but not in `biden`.

**Comment by mbouffard1** [comment]
Yes I realize that and that is just the same function as the one in Analyze_Book. I want to change it so that along with the words I also still get their frequencies. But if you do it with just the keys all it returns is a long list of words and I dont know how many times each one was used.

**Comment by lzblack** [comment]
Then keep the `.items()`. 

In `main`, you can use
```
    for word in diff:
        print(word[0], end=' ')
```
to print out the words only (not the freq)

**Comment by mbouffard1** [comment]
But I want the frequencies because I am looking to form a list of the top 20-30 words

**Comment by lzblack** [comment]
> But I want the frequencies because I am looking to form a list of the top 20-30 words

Your original code already included both words and freq.

**Comment by mbouffard1** [comment]
I think when I run that it just generates the same as the histogram but in the form of a tuple not a dict. I think when it looks at the items it is considering the word and the freq which means no matter what they are different? I am not sure but I dont think that it actually does what I want it to do. Like for instance if I run the trump one "politician" and general words like that come up that I would be surprised if it wasn't in the Biden article too.

**Comment by lzblack** [comment]
If you want to return a dict:
```
def exclusive_dict(d1,d2): 
     """Returns a dictionary with all keys that appear in d1 but not d2. 
     d1, d2: dictionaries 
     """ 
     res = {} 
     for word, freq in d1.items(): 
         if word not in d2: 
             res[word] = freq
     return res 
```

As regards your concern about common words, you need to design a better way to check that.

**Comment by mbouffard1** [comment]
Actually that code you just gave me generated a much shorter dict than what I had returned in the code I wrote. I think that is a much better way. Thanks professor
