### ISSUE TITLE
I am wondering if I can write a function off of this one that pulls only the sentences that have a negative sentiment so I can compare the difference between the negativity in Biden and in Trump. I was planning on looking at a few paragraphs or something, but since i get an output of every sentence it is hard to analyze. 

### ISSUE THREAD

**Issue by mbouffard1** [mbouffard1/text-mining#2]
https://github.com/mbouffard1/text-mining/blob/84a9a00c84daa97735deeecd2220c58c170b7c96/work%20with%20data/sentiment_trump.py#L19-L29

**Comment by lzblack** [comment]
> only the sentences that have a negative sentiment` 
> 

Actually most sentences would contain negative sentiment. I am not sure how you "compare the difference" - by average sentiment score of all the sentences? by one single sentiment score of the entire text (so you don't need to tokenize the text to list of sentences)?

**Comment by mbouffard1** [comment]
well I was looking through both and found ways to somewhat generate the sentences that had a negative score and it wasn't near all of them it was probably less than half. My goal is I just want the negative sentences so I can compare the negative sentiment in the trump intro to the biden intro. My problem is I can't find a way to generate just the sentences that are negative and their scores.

**Comment by lzblack** [comment]
So what you can do is create a list to keep all the "negative sentences" - this depends on how you define a negative sentence. You could check the negativity score only, which is `ss['neg']`, or compound score, which is `ss['compound']`.

**Comment by mbouffard1** [comment]
will I be able to print the sentences with them?

**Comment by lzblack** [comment]
> will I be able to print the sentences with them?

You probably want to consider a list of tuples, ie. `[('a sentence example', 0.4), ('...', -0.3),...]`
